# Generated by Django 5.2.8 on 2025-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
