# Generated by Django 5.2.8 on 2025-11-30 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_genres_animes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CW', 'Currently Watching'), ('PW', 'Plan to Watch'), ('C', 'Completed')], max_length=2)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.animes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.userdata')),
            ],
        ),
    ]
