# Generated by Django 5.2.8 on 2025-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_useranime'),
    ]

    operations = [
        migrations.AddField(
            model_name='animes',
            name='link',
            field=models.URLField(default='https://hianimez.is', max_length=500),
        ),
    ]
